import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Layout from '../components/Layout'
import withSession from '../lib/session'

export const getServerSideProps = withSession(async (ctx) => {
  const { req } = ctx;


  const authenticated = req.session.get('authen');

  if (!authenticated || !authenticated.isLoggedIn)
    return { redirect: { destination: '/login', permanent: false } };

  if (authenticated.isLoggedIn) {
    return { props: {} };
  }
});


function Home() {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>User NextJS App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>
            NextJS for <a href="/"> Users app!</a>
          </h1>
        </main>
      </div>
    </Layout>
  )
}
export default Home
