import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import { useSelector } from 'react-redux';
import { useEffect } from 'react';
import router from 'next/router';

export default function Home() {
  const authenticated = useSelector((state) => state.base.isAuthenticated);
  const base = useSelector((state) => state.base);
  useEffect(() => {
    console.log('Base reducer', base);

    if (!authenticated) {
      router.push('/login')
    }
  }, [authenticated])


  return (
    <div className={styles.container}>
      <Head>
        <title>User NextJS App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>

      <main className={styles.main}>
        <h1 className={styles.title}>
          NextJS for <a href="/"> Users app!</a>
        </h1>
      </main>

    </div>
  )
}
