import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'

export default function Home() {
  //TODO
  // useSelector => user
  // useEffect(() => {
  //   if (!(user) {
  //     router.push('/login')
  //   }
  // }, [user])

  return (
    <div className={styles.container}>
      <Head>
        <title>User NextJS App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>

      <main className={styles.main}>
        <h1 className={styles.title}>
          NextJS for <a href="/"> Users app!</a>
        </h1>
      </main>

    </div>
  )
}
